### ISSUE TITLE
Nonfunctional nvidia-docker install due to this lib

### ISSUE THREAD

**Issue by berkgercek** [pop-os/libnvidia-container#8]
Hello,

As [referenced in this issue](https://github.com/NVIDIA/nvidia-docker/issues/1660) when attempting to install `nvidia-docker2` via `apt` in Pop OS! the container runtime is unable to access GPUs on the machine due to a compilation error. 

Would it possible to remedy this? Also the current version of nvidia-docker2 provided by Pop is several months out of date and could use an update.

**Comment by berkgercek** [comment]
@elezar This is the issue I was referencing

**Comment by elezar** [comment]
As discussed in https://github.com/pop-os/nvidia-docker/issues/3 the issue seems to be with the fork and not the original repo.

@mmstick what is preventing these repos from being updated -- or even the upstream packages being used directly?

**Comment by mmstick** [comment]
@elezar I am actually updating from 1.11 to 1.12 right now. I do not know what the issue is though. It's not easy to package.

The packages from NVIDIA aren't built with standard Debian packaging tools. They seem to have a custom infrastructure with some dependencies that don't readily compile on 22.04.

Packages can't be pulled from another repository directly. They have to be buildable from source with `sbuild` in an offline environment.

**Comment by berkgercek** [comment]
If that's the case then for the moment might it not be better to stop providing the package through Pop distribution channels? As it stands installing a functional version requires overriding apt priorities to allow a manually-added nvidia source to take precedence

**Comment by berkgercek** [comment]
Can confirm this solves the issue downstream on nvidia-docker2 installed from Pop repos. Thanks @mmstick , @elezar !
